### ISSUE TITLE
Update mime due to vulnerability

### ISSUE THREAD

**Issue by dscalzi** [bowheart/ejs-electron#10]
There is currently a security vulnerability in mime.

Issue is patched with v1.4.1+ on the 1.x release line.
Issue is patched with v2.0.3 on the 2.x release line.

ejs-electron is currently on an affected version. https://github.com/bowheart/ejs-electron/blob/master/package.json#L9

More Information
https://nodesecurity.io/advisories/535

**Comment by bowheart** [comment]
Cool! Just published [a patch](https://github.com/bowheart/ejs-electron/commit/3f9ba5ea9708696543b61533fbb9820ea5585bca) for this. To fix, install `ejs-electron@2.0.2`. No more foolish security vulnerabilities. :lock: 

Thanks!
