### ISSUE TITLE
Buffer() Issue

### ISSUE THREAD

**Issue by ghost** [bowheart/ejs-electron#16]
(node:58832) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:58832) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by ghost** [comment]
I've made a PR with the fix for this.

**Comment by bowheart** [comment]
Cool, thanks! I did not see that the constructor had been deprecated. Will merge the fix later today (if I don't forget) in case anyone has any comments on the PR thread (#17). Closing this issue.
