### ISSUE TITLE
how to load new page

### ISSUE THREAD

**Issue by Proxy-99** [bowheart/ejs-electron#21]
like this 
`        <a href="login.ejs">test</a>
`

it does not render the page for me

**Comment by Proxy-99** [comment]
just remove that line of code will reslove the issue
`<% ejse.stopListening() %>`

😢

**Comment by bowheart** [comment]
Hello @Proxy-99! I just threw together a quick electron repo to test this for you. I have the following structure:

```
package.json
src/
  index.ejs
  login.ejs
  main.js
```

`package.json`:

```
{
  "name": "electron-test",
  "version": "1.0.0",
  "main": "src/main.js",
  "scripts": {
    "start": "electron ."
  },
  "dependencies": {
    "ejs-electron": "^2.1.1",
    "electron": "^24.0.0"
  }
}
```

`src/index.ejs`:

```ejs
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <h1>Hello <%= username %></h1>
    <a href="login.ejs">Login</a>
  </body>
</html
```

`src/login.ejs`:

```ejs
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <h1>This is the login page, <%= username %></h1>
    <a href="index.ejs">Back</a>
  </body>
</html>
```

`src/main.js`:

```
const { app, BrowserWindow } = require('electron')
const ejse = require('ejs-electron')

ejse.data('username', 'Proxy-99')

app.whenReady().then(() => {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
  })

  mainWindow.loadFile('src/index.ejs')
})
```

It looks like everything works exactly as I'd expect with your exact link. On load, the app looks like this:

<img width="802" alt="Screen Shot 2023-04-08 at 11 39 46 PM" src="https://user-images.githubusercontent.com/13201747/230752925-efcd52a2-d94d-43df-9f2e-9315d8f07b08.png">

After clicking the `Login` link, the `login.ejs` file is loaded up as expected. That looks like this:

<img width="802" alt="Screen Shot 2023-04-08 at 11 39 53 PM" src="https://user-images.githubusercontent.com/13201747/230752957-121a5d0c-548a-4dbc-8c1e-80bed594ba06.png">

If you can set up a sample repo, I can take a look at exactly what's happening in your case, but it looks like the code you posted should work if your folder structure is setup correctly. Also double-check that you're on the latest version of `ejs-electron` (v2.1.1) and at least a fairly recent version of electron (my test was on electron v24.0.0). Cheers

**Comment by bowheart** [comment]
Ah you figured it out before I commented.

I see that you probably copied that `.stopListening()` code from the README. I should probably structure the README better to not show an unnecessary code example so prominently like that. Sorry this bit you, I'll try to get around to improving the README next week.

**Comment by Proxy-99** [comment]
> Ah you figured it out before I commented.
> 
> I see that you probably copied that `.stopListening()` code from the README. I should probably structure the README better to not show an unnecessary code example so prominently like that. Sorry this bit you, I'll try to get around to improving the README next week.

yeah I used that, I think it's better to add a clear note about this function to avoid confusion in future. and thanks for help!
