### ISSUE TITLE
Binary files, like images, get intercepted and turned into strings

### ISSUE THREAD

**Issue by gmcdev** [bowheart/ejs-electron#5]
Hi there -

Thanks for this module. It really helped jump-start this migration to Electron that I had to do.

However, I came across a couple of( at least in my build what appeared to be )deficiencies. Your intercept function was messing up the file structure of binary requests. Also the async-file-read I think was causing the browser to give up on the request or something, because that was the final thing I changed to get everything singing.

https://gist.github.com/gmcdev/661f259ad82165421a4fe41b51e8102d

Changelog:
- intercept Buffers instead
- open synchronously
- render ejs files and return to a Buffer state
- return with the correct mime-type per extension( requires npm mime )

**Comment by bowheart** [comment]
Hey, thanks for this.  Your suggestions are actually extremely helpful.  `ejs-electron` is still in development, of course, as there hasn't been a major release yet.  I'm still trying to get a feel for what people want it to do and how they want the API to look.

I've implemented all your suggestions in another minor release, v0.3.0.  I wasn't sure about the "open synchronously" bit, but if you say it was causing problems in async, then we'll try it this way for a bit and see what people think.

Thanks again for your feedback
