### ISSUE TITLE
Spaces in path nor working

### ISSUE THREAD

**Issue by GrishaevPavel** [bowheart/ejs-electron#8]
Hello!
function parsePathname do not replace %20 into spaces, so teplate can't be loaded.
Make this maybe:

`function parsePathname(reqUrl) {
	let parsed = url.parse(reqUrl)
	let pathname = **decodeURIComponent**( parsed.pathname )

	if (process.platform === 'win32' && !parsed.host.trim()) {
		pathname = pathname.substr(1)
	}
	return pathname
}`

**Comment by bowheart** [comment]
Ah. You are absolutely right. Good catch.
